baseURL = 'https://serpentos.com/'
title = 'Serpent OS'
contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
# Configure how URLs look like per section.
[permalinks]
  blog = '/:section/:year/:month/:day/:slug/'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[module]
proxy = "direct"


[[module.imports]]
path = "github.com/google/docsy"

[params]
github_repo = "https://github.com/serpent-os/serpentos.com"
offlineSearch = true
description = "Serpent OS is a modern, powerful, and open-source operating system that aims to be the best in class."

[params.ui]
navbar_logo = false
ui_show = 1
sidebar_menu_compact = true
showLightDarkModeMenu = true

[[menu.main]]
    name = "About"
    weight = 20
    url = "/about"

[[menu.main]]
    name = "Community"
    weight = 30
    url = "/community"

[[menu.main]]
    name = "Download"
    weight = 40
    url = "/download"

[[menu.main]]
    name = "Documentation"
    weight = 50
    url = "/docs"

[[menu.main]]
    name = "Sponsor"
    weight = 60
    url = "/sponsor"

[[params.links.user]]
    name = "Matrix Space"
    url = "https://matrix.to/#/!trFJOzhpDUejJKnPYg:matrix.org"
    desc = "Discussions and support for Serpent OS in real time"
    icon = "fa fa-circle-question"

[[params.links.user]]

    name = "GitHub Discussions"
    url = "https://github.com/orgs/serpent-os/discussions"
    desc = "Developer & user discussions"
    icon = "fa fa-comments"

[[params.links.user]]
    name = "Bluesky"
    url = "https://bsky.app/profile/serpentos.bsky.social"
    icon = "fab fa-bluesky"
    desc = "Latest updates and posts from the team"

[[params.links.user]]
    name = "Mastodon"
    url = "https://fosstodon.org/@serpentos"
    icon = "fab fa-mastodon"
    desc = "Latest toots and thoughts from the team"

[[params.links.developer]]

    name = "GitHub"
    url = "https://github.com/serpent-os"
    desc = "Home of all Serpent OS repositories"
    icon = "fab fa-github"

[[params.links.developer]]
    name = "Build"
    url = "https://dash.serpentos.com/tasks"
    desc = "Dashboard for current package builds"
    icon = "fa fa-truck-fast"

[[params.links.developer]]
    name = "Sponsor"
    url = "/sponsor"
    desc = "Dollars for developers"
    icon = "fa fa-heart"
