site_name: Serpent OS
theme:
    features:
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.footer
    name: material
    palette:
        scheme: slate
        primary: black
        accent: light blue
    logo: static/logo_white.webp
    favicon: static/favicon.png
plugins:
    - blog:
        authors: true
        post_date_format: full
    - rss:
        match_path: blog/posts/.* 
        date_from_meta:
            as_creation: date
        categories:
            - categories
            - tags 
copyright: |
    <div>Copyright &copy; 2023 Ikey Doherty, Serpent OS Developers</div>

    <a href="#__consent">Change cookie settings</a>
extra:
    consent:
        title: Cookie consent
        description: |
            This website makes use of cookies to improve your experience
            while navigating our website and documentation.
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/serpent-os
        - icon: fontawesome/brands/mastodon
          link: https://fosstodon.org/@serpentos
        - icon: fontawesome/brands/x-twitter
          link: https://twitter.com/Serpent_OS
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/channel/UCyGjpLXzRZdkD0Uc_uZJmaQ
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
