authors:
    ikey:
        name: Ikey Doherty
        description: Founder
        avatar: https://avatars.githubusercontent.com/u/53261402
    ermo:
        name: Rune Morling
        description: Co-architect, Process Guy
        avatar: https://avatars.githubusercontent.com/u/118045
    sunnyflunk:
        name: Peter O'Connor
        description: Performance Guy
        avatar: https://avatars.githubusercontent.com/u/19542864